version: "3"
services:
  php:
    build:
      context: .
      target: builder
      dockerfile: Docker/php/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./Docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./Docker/php/logs:/var/log/apache2
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - driving
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8282:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - driving
  mysql:
    build:
      context: .
      dockerfile: Docker/mysql/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: billing
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/tables:/docker-entrypoint-initdb.d
    networks:
      - driving
networks:
  driving:
volumes:
  mysql_data:
