version: "3"
services:
  php:
    build:
      context: .
      target: builder
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - driving
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8282:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    networks:
      - driving
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - driving
networks:
  driving:
volumes:
  mysql_data:
